let content_Database = {
    cD_Title: [
        /*001*/'Mark Hughes: Błyskotliwość Piastriego wciąż zaskakuje McLarena',
        /*002*/'Wyjątkowa szansa Piastriego na położenie Markera Verstappen',
        /*003*/'Szczegółowo: Niewiarygodna jazda MOTOGP',
        /*004*/'"Balansowanie nożem na czubku" - wymowna analogia samochodu Hamiltona',
        /*005*/'Duet Ducati Doznał złamań w sobotnim wypadku GP Indii',
        /*006*/'Jak Leclerc odwrócił scenariusz Ferrari na Suzuce',
        /*007*/'Kosztowna awaria Sargeanta będzie dodatkowym niekorzystnym rozwiązaniem',
        /*008*/'Marko dostaje ostrzeżenie FIA za obraźliwą uwagę Pereza',
        /*009*/'Varstappen zdobywa pole position Suzuka przed Piastri',
        /*010*/'Ducati 1-2-3-4 w inanguracyjnych kwalifikacjach MOTOGP w Indiach',
        /*011*/'"Okropny" upał skłania MotoGP do skrócenia dystansu wyścigu GP Indii',
        /*012*/'Dlaczego Lawson nie mógł przebić się do składu Alphataori 2024',
        /*013*/'Podcast: Zwycięzca MotoGP Hondy o tym, co Marquez powinien zrobić dalej',
        /*014*/'Sekcja komentarzy do wyścigu zmienia się',
        /*015*/'Gary Andersen: Jak i dalczego zespoły F1 forsują zasady elestycznego nadwozia'
    ],
    cD_Description: [
        /*001*/'Oscar Piastri znakomicie spisywał się podczas swojej pierwszej wizyty na Suzuka, a nawet zaskoczył zespół McLarena, który już zwiększył swoje oczekiwania wobec swojego gwiazdorskiego debiutanta. Mark Hughes również jest pod wrażeniem, gdy wyjaśnia błyskotliwość Piastriego.',
        // https://www.the-race.com/formula-1/mark-hughes-piastris-brilliance-is-still-surprising-mclaren/
        /*002*/'Oscar Piastri ma okazję niewielu kierowców przeciwko Maxowi Verstappenowi, aby wypowiedzieć się w Grand Prix Japonii Formuły 1. Podczas gdy Piastri znajduje się po złej stronie stawki, najnowsza historia sugeruje, że wyzwanie w zakręcie nr 1 jest co najmniej możliwe. A jego pół żart na wpół żart zaraz po zdobyciu pierwszego miejsca w pierwszym rzędzie w F1 mówił wszystko: "Jest tylko jeden samochód przed wyprzedzaniem, więc postaram się to zrobić". Jeśli Piastri dostanie powąchać, stawia to Verstappena w nietypowej sytuacji – nie wie, czego się spodziewać po tym kierowcy. Tak więc Piastri ma niepowtarzalną szansę na położenie znacznika. Weźmy pod uwagę kierowców, z którymi Verstappen szedł koło w koło w ostatnich latach: Lewis Hamilton, Charles Leclerc, George Russell i tak dalej. Albo zna ich z wyścigów przed F1, rozwinął wyraźne zrozumienie ich stylu walki w samej F1 - albo jedno i drugie. W przypadku Lando Norrisa jest tam przyjaźń, a także głębokie wzajemne zrozumienie dla ich jazdy z ich simracingowych przedsięwzięć. Verstappen pokazał, że jest zdolny do agresywnego, zastraszającego stylu przeciwko kierowcom, których czuje, że może zdominować lub z którymi czuje, że musi coś powiedzieć. Daje innym (czy to dlatego, że ma wcześniej istniejący związek, nie uważa ich za zagrożenie – cokolwiek) trochę więcej miejsca. Niewiele, ale więcej.',
        /*003*/'Piąte miejsce Marco Bezzecchiego w sprincie MotoGP w Indiach zostało nagrodzone pięcioma punktami, ponieważ został odsunięty od dwóch zawodników przed nim w klasyfikacji, Pecco Bagnaia i Jorge Martina. Była to również bardziej imponująca jazda niż niejedna rzeczywista wygrana w Grand Prix - i prawdopodobnie również bardziej pamiętna.',
        /*004*/'Lewis Hamilton nie cieszył się ostatnimi sesjami kwalifikacyjnymi w samochodzie Formuły 1 Mercedesa, który opisał jako "próbę zrównoważenia noża na czubku". I chociaż występ zespołu w Japonii nie był powodem do świętowania, a Hamilton i George Russell zakwalifikowali się na siódmym i ósmym miejscu ze stratą sekundy, Hamilton przynajmniej miał bardziej komfortowe wyczucie w samochodzie prawdopodobnie po raz pierwszy po tej stronie letniej przerwy. Siedmiokrotny mistrz świata był ostatnio dość samokrytyczny, przyznając, że jego występy kwalifikacyjne nie spełniały jego zwykłych standardów, a jego kolega z zespołu Russell cieszył się z poprawy formy. Pokonanie Russella o trzy dziesiąte na Suzuce jednoznacznie zakończyło jednak ten krótki przejazd. Hamilton zamienił deficyt na początku weekendu w wyraźną przewagę w kwalifikacjach, gdzie wyglądał znacznie swobodniej w samochodzie, który wydawał się prawie lubić prowadzić. "Wczorajszy dzień był koszmarem" - powiedział Hamilton po kwalifikacjach na początku szybkiej wymiany zdań z The Race.',  
        /*005*/'Dwóch zawodników Ducati, którzy doznali złamań w wypadkach podczas inauguracyjnego weekendu Grand Prix Indii MotoGP, a Luca Marini dołączył do Alexa Marqueza przy linii bocznej. Marini uderzył w kolegę z zespołu VR46 Ducati i protegowanego Valentino Rossiego, Marco Bezzecchiego w pierwszym zakręcie wyścigu sprinterskiego i udał się do centrum medycznego na Buddh International Circuit na kontrolę.',
        /*006*/'Wewnątrzespołowa walka w Ferrari była jednokierunkowa od sierpniowej przerwy w Formule 1, z Carlosem Sainzem na czele. Jednak w kwalifikacjach do Grand Prix Japonii Charles Leclerc odwrócił ten trend, wyprzedzając swojego kolegę z zespołu o 0,309 s.',
        /*007*/'Wypadek Logana Sargeanta w kwalifikacjach do Grand Prix Japonii tylko pogorszy niefortunną rozbieżność między specyfikacjami samochodu Formuły 1 Williamsa jego kolegi z zespołu, Alexa Albona. Sargeant wciąż walczy o utrzymanie się w końcowej części swojego debiutanckiego sezonu F1, ponieważ stara się przekonać Williamsa, aby zatrzymał go na 2024 rok. Mocno rozbił się, wchodząc na prostą startową na Suzuce w Q1, podczas gdy ukończył okrążenie, które było korzystne w porównaniu do Albona i przyznał, że "zdecydowanie nie było to pozytywne" mieć kolejną sesję, w której była wyraźna obietnica, że ostatecznie nie udało mu się wywiązać.',
        /*008*/'Marko otrzymał pisemne ostrzeżenie i przypomniał o swoich obowiązkach jako wybitnej postaci F1 zgodnie z kodeksem etycznym FIA. Wynika to z krytycznego i geograficznie niedokładnego twierdzenia, że niespójne występy Pereza w tym sezonie wynikają z tego, że jest "Amerykaninem z Ameryki Południowej". Po Grand Prix Włoch Marko zakwestionował rzekomą "meksykańską mentalność" Pereza w wywiadzie telewizyjnym na platformie Servus należącej do Red Bulla.',
        /*009*/'Max Verstappen i Red Bull wracają na szczyt w Formule 1 po zmiażdżeniu przeciwników w kwalifikacjach do Grand Prix Japonii. Nic nie wskazuje na powtórkę zmagań Red Bulla w Singapurze – gdzie oba samochody odpadły z Q2 – przez cały weekend i trwało to w kwalifikacjach, a Verstappen zapewnił sobie status faworyta pole position przez cały czas.',
        /*010*/'Marco Bezzecchi zdobył pole position do inauguracyjnego Grand Prix Indii MotoGP, a Ducati zamknęło pierwszą czwórkę. Pierwsze kwalifikacje w najwyższej klasie na Buddh, byłym torze Formuły 1, sprowadziły się do walki między Bezzecchim a innym kierowcą satelitarnym Ducati, Jorge Martinem. Pomimo kraksy w treningu przed kwalifikacjami - jeżdżąc w porysowanych skórach i ograniczając się do jednego motocykla - Martin prowadził Pramaca po pierwszych próbach w strzelaniu z pole drive. Ale to było tylko z 1m44.153s, i podczas gdy zarówno on, jak i Bezzecchi ostatecznie dostali się do zakresu 1m43s, Bezzecchi 1m43.947s ostatecznie skończył o pół dziesiątej lepiej. Lider mistrzostw Pecco Bagnaia zapewnił sobie ostatnie miejsce w pierwszym rzędzie z przewagą 0,012 s nad kolegą Bezzecchiego z zespołu VR46, Lucą Marinim.',
        /*011*/'Grand Prix Indii w ten weekend zostanie skrócone o trzy okrążenia po porozumieniu między zawodnikami, zespołami, organizatorami i dostawcami opon, a ekstremalne warunki pogodowe na Buddh International Circuit odcisnęły swoje piętno na wszystkich dzięki nieoczekiwanie wysokiej temperaturze i wilgotności, które sprawiły, że zawodnicy szczególnie zmagają się fizycznie.',
        /*012*/'Problemy Red Bulla z trzema na dwóch w drugim składzie kierowców Formuły 1 zostały rozwiązane, a Yuki Tsunoda i Daniel Ricciardo potwierdzili to w AlphaTauri w 2024 roku, a Liam Lawson musiał na razie czekać na miejsce w pełnym wymiarze godzin. Przedłużenie Tsunody mogło być przedmiotem spekulacji, gdy się przeciągało, ale było to wątpliwe, jeśli Honda zdecydowała się nie wspierać go dalej, co zawsze wydawało się bardzo mało prawdopodobne.',
        /*013*/'W najnowszym wydaniu "Toby Talks To" gospodarz Toby Moody siada do rozmowy z Carlosem Checą, zawodnikiem, który ścigał się w 125, 250 i 500, gdy najwyższa klasa przekształciła się w kategorię, którą znamy jako MotoGP w 2002 roku. Popularny Hiszpan otwiera się na wzloty i upadki swojej kariery, w tym dwa zwycięstwa w Grand Prix 500cc dla Hondy na rodzimej ziemi w Barcelonie i Jaramie oraz tytuł mistrza świata Superbike, który zdobył po przejściu z MotoGP.Omawia również, jak to jest być kolegą zespołowym z Valentino Rossim i przedstawia swoją opinię na temat obecnej sytuacji rodaka Marca Marqueza w Hondzie - w tym jego pogląd na to, co powinien zrobić dalej.',
        /*014*/'Drodzy Czytelnicy, Od 19 września komentowanie artykułów na temat The Racetop będzie zarezerwowane tylko dla członków. Poprawi to jakość dyskusji, usunie wszelkie posty botów lub wielu właścicieli kont, a także pozwoli naszym dziennikarzom uczestniczyć w debatach.',
        /*016*/'Elastyczne nadwozie jest częścią Formuły 1 od dłuższego czasu i pozostanie nim pomimo najnowszej dyrektywy technicznej FIA, która wejdzie w życie podczas Grand Prix Singapuru w ten weekend. Przepisy brzmią dość prosto. Artykuł 3.2.2 wymaga, aby wszystkie elementy aerodynamiczne "były sztywno zabezpieczone i nieruchome" oraz "tworzyły jednolitą, solidną, twardą, ciągłą, nieprzepuszczalną powierzchnię w każdych okolicznościach". Ale rzeczywistość jest taka, że nigdy nie będziesz mieć komponentu poddawanego różnym obciążeniom, który jest całkowicie sztywny. Dlatego musi istnieć przynajmniej jakiś ruch, który jest sprzeczny z literą prawa.'
    ]
};
